### ISSUE TITLE
Get the title better

### ISSUE THREAD

**Issue by mohamadnr** [amarinediary/Where-Is-My-Bread#1]
Sometimes `url_to_postid` cannot retrieve the title of the page despite the page's existence, it happened for me in the archive page. It can also try to get the title using the slug if couldn't find it via the URL.
So I added this code:
```
if ($id = url_to_postid($crumb->url))
	$title = get_the_title($id);
elseif ($id = get_page_by_path($crumb->slug)->ID)
	$title = get_the_title($id);
```
and changed the value inside the `span` to this:
```
 ((isset($title)) ? $title : ucfirst(str_replace('-', ' ', $crumb->slug)))
```
Seems better to me.

**Comment by amarinediary** [comment]
Thank you for your input @mohamadnr.
Indeed it seems logic to have a fallback. I wasn’t aware that `url_to_postid` was failing from time to time. I will update the original file as soon as I can.

**Comment by amarinediary** [comment]
Credit for the `get_page_by_path()` usage was given to you in the 1.0.2 version as a comment line on the main branch.
