### ISSUE TITLE
WooCommerce 

### ISSUE THREAD

**Issue by buildpress** [amarinediary/Where-Is-My-Bread#12]
Hi there,

Thanks for the great work. I installed and use it but face the issue that WooCommerce is not compatible here.
As you select the bread based on Taxonomie; The Url structure is:

Home > Product > Product Description

Although it should be:

Home > Categorie Archive > Product Description

Joep

**Comment by amarinediary** [comment]
Hi @joomapp, glad you like it.

I'm not sure I understand the issue. Is there a missmatch between the url and the output ?

Try to be as precise as possible, I need to be able to reproduce the issue on my end.

FYI, you can intercept the crumbs array to modify/update a crumb. See [Intercepting the crumbs array](https://github.com/amarinediary/WordPress-simple-URL-based-breadcrumb#example-intercepting-the-crumbs-array).

```
<?php

$crumbs = get_the_crumbs();

array_walk( $crumbs, function( &$value, $key ) {

    if ( 'something' == $value['slug'] ) {

        $value['slug'] = 'somethingelse';

    };

} );

$ingredients = array(
    'crumbs' => $crumbs,
);

the_bread( $ingredients );
```

**Comment by amarinediary** [comment]
No news means good news, I'm closing this one !
For future reference: Opening an issue and not participating might be considered rude.
