### ISSUE TITLE
Category slug isn't named correctly

### ISSUE THREAD

**Issue by nikolailehbrink** [amarinediary/Where-Is-My-Bread#13]
Hi there, it is me again.
I think I discovered another bug.

We have posts in a category called "Experten-Beiträge". Now when I go to the page and consider the categories in the permalink structure, the category names are not displayed correctly. I have made a few screenshots, which describes the problem.

I would like to have the correct category name displayed, rather than a mixture of name and slug (looks like it is a mixture somehow)
<img width="498" alt="Bildschirmfoto 2022-12-15 um 12 30 09" src="https://user-images.githubusercontent.com/38915700/207849991-5fd2ad3f-b2d6-4f3e-a261-dd7a094a0055.png">
<img width="919" alt="Bildschirmfoto 2022-12-15 um 12 31 09" src="https://user-images.githubusercontent.com/38915700/207849996-d2421676-0810-4f77-b96f-b220211a24c5.png">
<img width="1580" alt="Bildschirmfoto 2022-12-15 um 12 38 16" src="https://user-images.githubusercontent.com/38915700/207849998-46ffe827-fa5e-4b50-82a2-8a8766c8c6ba.png">

**Comment by amarinediary** [comment]
Hi @nikolailehbrink,
A few questions to help me understand the problem:
- When you're on the "Der Gen Z auf der Spur" post, what is the permalink being displayed ?
- What do you mean by a "mixture of name and slug" ? What is the current result ? What's the expected result ?
- Can you give me a the taxonomy architecture ?

**Comment by nikolailehbrink** [comment]
Hi @amarinediary,

> * When you're on the "Der Gen Z auf der Spur" post, what is the permalink being displayed ?

the permalink that is displayed is: https://stage.moskito.de/news/experten-beitraege/genz/

> * What do you mean by a "mixture of name and slug" ? What is the current result ? What's the expected result ?*

If you look at the screenshots, then the output of the breadcrumbs is "Startseite -> KOSmos -> Experten beitraege -> Der GenZ auf der Spur". Now the category slug, which you can also see in another screenshot is "experten-beitraege".  I don't know where the plugin for example gets the first upper case letter because it is not in the category slug and also the dash between the two words is missing. However that should not be my problem and I just thought that this is a wierd behaviour.

Current result:
`Startseite -> KOSmos -> Experten beitraege -> Der GenZ auf der Spur`

Here is what the desired output is:
`Startseite -> KOSmos -> Expert:innen-Beiträge -> Der GenZ auf der Spur`

So it is just the name of the category instead of the slug.

> * Can you give me a the taxonomy architecture ?

I don't have any more information than what I send you with the opening of this ticket :)

Thank you

**Comment by amarinediary** [comment]
Awesome @nikolailehbrink I know what's happening, that's not per say a bug but a feature ! Aha

I made this for a personal project a while back and I never expected the success it would get.

This plugin is just a glorified URL parser. But there is a few interesting things happening:

1. The plugin will examines the URL and try to determine the post ID it represents.
2. The plugin will try to retrieves a page object given its path.
3. The plugin will fallback to parsing the last slug, sanitizing the title by removing any dashes, and finally capitalizing the first character.

Why are you ending up in situation 3 ? Because you're German. And NO that's not because of WW2 but because of characters encoding.

There is a few characters that are not allowed in URLs of which `ä` and `:` are part of.

Now that you've mentioned it, I will look at retrieving the taxonomy name and terms name from the term/taxonomy URLs instead of a sanitized version of the slug. Very interesting.

But meanwhile you could use [Intercepting the crumbs array](https://github.com/amarinediary/WordPress-simple-URL-based-breadcrumb#example-intercepting-the-crumbs-array):

```php
<?php

$crumbs = get_the_crumbs();

array_walk( $crumbs, function( &$value, $key ) {

    if ( 'Experten beitraege' == $value['slug'] ) {

        $value['slug'] = 'Expert:innen-Beiträge';

    };

} );

$ingredients = array(
    'crumbs' => $crumbs,
);

the_bread( $ingredients );
```

Keep me up to date, let me know if that fixes thing on your end.

**Comment by nikolailehbrink** [comment]
Hi @amarinediary thanks for your reply!
I get the problem! I could get it almost to work with the following code:

```php
<?php
if ((!is_front_page() && !is_home())) {
    $crumbs = get_the_crumbs();

    array_walk($crumbs, function (&$value, $key) {
        error_log($value['slug']);

        if ('experten-beitraege' == $value['slug']) {
            $value['slug'] = 'Expert:innen-Beiträge';
        };
    });
    $ingredients = array(
        'crumbs' => $crumbs,
        'separator' => '→',
        'root' => array(
            'slug' => 'Start',
            'url' => get_home_url(),
        ),
    );
    the_bread($ingredients);
}
?>
```
However the dash is still stripped away and the breadcrumb looks like in the screenshot:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/38915700/208895623-6279062f-68d3-491d-a161-8ab0dbb12745.png">

Would be nice, if you could look into it one more time. :)

**Comment by amarinediary** [comment]
I think the easiest for you would be to write your own custom `the_custom_bread` function.

We duplicate `the_bread `function and customize it. Bellow is an example that could suits your needs.

Look for the "Fallback." in the code bellow.

```php
if ( ! function_exists( 'the_custom_bread' ) ) {

    function the_custom_bread( $ingredients = array() ) {

        if ( empty( $ingredients['crumbs'] ) ) {
        
            $crumbs = get_the_crumbs();
            
        } else {
        
            $crumbs = $ingredients['crumbs'];
            
        };

        if ( empty( $ingredients['root'] ) ) {
        
            $root = null;
            
        } else {
        
            $root = $ingredients['root'];
            
        };
        
        if ( empty( $ingredients['offset'] ) ) {
        
            $offset = 0;
            
        } else {
        
            $offset = $ingredients['offset'];
            
        };
               
        if ( empty( $ingredients['length'] ) ) {
        
            $length = null;
            
        } else {
        
            $length = $ingredients['length'];
            
        };

        /**
         * Handling the root crumb case. 
         * Prepend one or more elements to the beginning of an array.
         * @see https://www.php.net/manual/en/function.array-unshift.php
         */
        if ( ! empty( $root ) ) {

            array_unshift( $crumbs, $ingredients['root'] );

        };
        
        /**
         * Handling the length case.
         * Extract a slice of the array.
         * @see https://www.php.net/manual/en/function.array-slice.php
         */
        $crumbs = array_slice( $crumbs, $offset, $length );

        if ( ! empty( $crumbs ) ) {

            echo '<ol class="🍞 bread" itemscope itemtype="https://schema.org/BreadcrumbList">';

            $i = 0;
            
            foreach ( $crumbs as $crumb ) {

                $i++;

                /**
                 * Unparsing the slug.
                 */
                if ( url_to_postid( $crumb['url'] ) ) {

                    $title = get_the_title( url_to_postid( $crumb['url'] ) );

                } elseif ( get_page_by_path( $crumb['slug'] ) ) {

                    $title = get_the_title( get_page_by_path( $crumb['slug'] ) );

                } else {
  
                    /**
                     * Fallback.
                     */
                    $title = $crumb['slug']
                    //$title = ucfirst( str_replace( '-', ' ', $crumb['slug'] ) );

                };

                echo '<li class="crumb" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                    <a itemprop="item" href="' . $crumb['url'] . '">
                        <span itemprop="name">' . $title . '</span>
                    </a>
                    <meta itemprop="position" content="' . $i . '">
                </li>';

                if ( $i !== sizeof( $crumbs ) && ! empty( $ingredients['separator'] ) ) {

                    echo $ingredients['separator'];

                };
    
            };
    
            echo '</ol>';

        };

    };

};
```

**Comment by nikolailehbrink** [comment]
Hi, I pasted the code inside my functions.php but there is no difference between both versions :)

**Comment by nikolailehbrink** [comment]
Could you integrate it in the plugin that it accepts the correct category name and not just guess it?
