### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by amarinediary** [amarinediary/Where-Is-My-Bread#15]
With 2023 and all those Ai tools, someone should consider running my code through ChatGPT (or any other tool) to do some :
- [ ] Code refactoring.
- [ ] Code minifying.
- [ ] Extensive error handling.
- [ ] In-depth code commenting.
- [ ] Other stuffs you might think of.
If nobody does it, I will try to do it for early summer 2023.

**Comment by mattmacneil** [comment]
I use this plugin here and there and it's been a big help to me. Every other solution is either underdeveloped and just spits out a list of parent pages until there aren't any more (which I'd rather just write myself), or super bloated for what is a relatively simple ask. This plugin is right in the sweet spot between the two poles.

The point is, I appreciate your work and I'd like to help. Subscribing to this - let me know if you still plan on doing any work here, I'd lend a hand when possible (with an AI tool or without).

I think there might be some native breadcrumb support in an upcoming WP release that might make this redundant? But until then I presume this repo will be one of the first things people find via your SO answer when Googling "wordpress breadcrumbs" so definitely worth keeping in good shape. Not that it's in bad shape right now lol but you know what I mean.

**Comment by amarinediary** [comment]
@mattmacneil First of all, thank you for the kind words.
I've taken some distance with WordPress nowadays so improvements are not happening that often. The project is open source, feel free to make it your own.
I've just released a [`1.2.4`](https://github.com/amarinediary/WordPress-simple-URL-based-breadcrumb/releases/tag/1.2.4). Some improvements have been made but nothing ground breaking. `1.2.4` has been released has a pre-release, I didn't had time to test it live.
Feel free to do so, and don't hesitate to pull and ask for merge if you can make valuable improvements.

**Comment by amarinediary** [comment]
#### `1.2.4`

`1.2.4` brings further improvements conditional logic based on the PHP version and further improvements. `1.2.4` hasn't been through any testing. Feedback for `1.2.4` is apreciated and more than welcome.

[`1.2.3`](https://github.com/amarinediary/WordPress-simple-URL-based-breadcrumb/releases/tag/1.2.3) remains the current most stable version. 

- [x] Introduced `safe_str_ends_with`. `safe_str_ends_with` uses the native PHP > 8.0.0 function when available, or falls back to the custom implementation.
- [x] Introduced `safe_str_contains`. `safe_str_contains` uses the native PHP > 8.0.0 function when available, or falls back to the custom implementation.
- [x] Introduced `attempt_to_retrieve_server_scheme`.
- [x] `get_the_crumbs` was updated to use introduced functions.
- [x] `the_bread` was updated. Improvements to how default parameters are introduced were made. The use of `extract()` saves us the trouble of writing multiple if statements.
- [x] Code commenting improvements.
- [x] Emphasis on [WordPress coding standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/). 
- [x] [README.md](https://github.com/amarinediary/WordPress-simple-URL-based-breadcrumb/blob/main/README.md) updates.
- Special thanks to [@mattmacneil](https://github.com/mattmacneil) for the feedback and kind words.
