### ISSUE TITLE
[Google Search Console] Error: Missing field "item"

### ISSUE THREAD

**Issue by ruzicic** [amarinediary/Where-Is-My-Bread#2]
Since I started using `where-is-my-bread`, Google Search Console started reporting these errors:

<img width="888" alt="Screenshot 2022-02-13 at 13 16 15" src="https://user-images.githubusercontent.com/15891813/153752650-8cd9f045-6725-499c-b718-4f410f6b3d2e.png">

One of many URLs that they report has this error is this one:
[https://studenti.rs/skripte/sociologija/umetnost/](https://studenti.rs/skripte/sociologija/umetnost/)

Here is the HTML output from Where Is My Bread for this page (removed `class` to improve readability):

```html
<ol itemscope="" itemtype="https://schema.org/BreadcrumbList">
	<li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
		<a itemprop="item" href="">
		<span itemprop="name">Skripte</span>
		</a>
		<meta itemprop="position" content="1">
	</li>
	<svg width="3" height="6" aria-hidden="true" >
		<path d="M0 0L3 3L0 6" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"></path>
	</svg>
	<li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
		<a itemprop="item" href="">
		<span itemprop="name">Sociologija</span>
		</a>
		<meta itemprop="position" content="2">
	</li>
	<svg width="3" height="6" aria-hidden="true" >
		<path d="M0 0L3 3L0 6" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"></path>
	</svg>
	<li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
		<a itemprop="item" href="">
		<span itemprop="name">Umetnost</span>
		</a>
		<meta itemprop="position" content="3">
	</li>
</ol>
```

When I use [validator.schema.org](https://validator.schema.org/), which is the tool that Google suggested for debugging, to test this URL - no errors were found. But, **there is an obvious error** - missing field.

Any ideas if this is specific for my website or a bug/missing feature of the plugin?

**Comment by amarinediary** [comment]
@ruzicic Very interesting. 

When I developed it, I used also the  Google Search Console Validation Tool which didn't returned any errors at that time. 

I've just tested it on [both tools (the Schema and Google one)](https://developers.google.com/search/docs/advanced/structured-data) and I'm now getting inconsistent results.

That might be due to a more recent update on the Google Search Console Validation Tool.

I'm taking an interest in the issue and will try to come up with a fix over the upcoming week.

**Comment by amarinediary** [comment]
I've made some testing. I'm now confident to say that the problem is coming from your end. The original example output is working on both validator.

Taking a closer look at your structure I can see that you're missing the `<li>` element:
```php
<li class="crumb" itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
```
I'm guessing you made some modification to the original file.

**Comment by ruzicic** [comment]
Thanks for taking an interest in this one!
Note: I suggest using only the provided code snippet for testing, as on the latest version of my website I actually did many customizations, to resolve reported issues.

But I can not argue if it was indeed coming from my side - you may be right. However, when I used it, it was the latest version without any changes made from my side.

**Comment by amarinediary** [comment]
Understood.

I've taken an additional look after your comments, and I'm now finally getting the same error as you are with the current version.

**Comment by amarinediary** [comment]
Your output is passing both verification without any issue.

I'm not able to reproduce tho I found a related post talking about that issue and discrepancies in between Validation tools and the Google Search console.

- see @ [How To Resolve Misattributed Errors In The New Google Search Console](https://www.schemaapp.com/schema-markup/how-to-resolve-misattributed-errors-in-the-new-google-search-console/)

Additionally note that apparently some errors fade after additional check from the Google Bot.

> [...] Our team has investigated a couple of instances where this search verifies that the markup is there, despite the disagreement with Search Console and has found a solution, where the errors decline steadily over the course of a few days, as seen here. [...]

> [...] Additionally, in our experience, it will not necessarily resolve all of the errors on the first validation, thus you may need to rerun the validation to resolve the remaining issues. [...]

You can also take a look at [Discrepancies in Google Search Console: Enhancement Reports vs. Performance Reports](https://support.schemaapp.com/support/solutions/articles/33000267425-discrepancies-in-google-search-console-enhancement-reports-vs-performance-reports).

I will also add a "Know Issues" section in the README.md.

If you're able to fix the issue I'm definitely interested in the answer and will update the source code according to your answer.

**Comment by amarinediary** [comment]
I've written a new section in regards to that issue with additional information:
- see @ [Discrepancies between Google Schema Validation tools and the Google Search Console Enhancement Reports and Performance Reports.](https://github.com/amarinediary/Where-Is-My-Bread#discrepancies-between-google-schema-validation-tools-and-the-google-search-console-enhancement-reports-and-performance-reports)
