### ISSUE TITLE
Display "Home" instead of Site URL 

### ISSUE THREAD

**Issue by hanyseyedy** [amarinediary/Where-Is-My-Bread#6]
hi,

It is better to use the phrase "Home" instead of Site URL in first item of breadcrumb. 
Displaying URL and deleting "dash" causes problems. For example, in other languages or RTL, is not suitable at all.
There is no necessity to display the site URL Instead of "home".
Always set the first item "Home". For example, this site: https://jannah.tielabs.com/demo/
In all types of pages or posts, the first item is "Home".

![001](https://user-images.githubusercontent.com/36000819/155438037-7f7ffd18-9782-480b-9b2a-ee22671d18d6.png)

![002](https://user-images.githubusercontent.com/36000819/155438074-2710c782-34b4-4ed1-b115-63de7abbc5a7.png)

Thank you very much if this is corrected.
It is really necessary.

Thank you very much for your time

**Comment by amarinediary** [comment]
I'm not sure I understand the issue.

You can set the root crumb slug and url yourself, and it will be prepended to the crumbs. See [Example: The bread with a root crumb](https://github.com/amarinediary/Where-Is-My-Bread#example-the-bread-with-a-root-crumb)

```
<?php

$ingredients = array(
    'root' => array(
        'slug' => 'home',
        'url' => get_home_url(),
    ),
);

the_bread( $ingredients );
```

And I think you're also asking why "category" isn't showing up ? Are you referring to: [Breadcrumb behaviour for post types and taxonomies](https://github.com/amarinediary/Where-Is-My-Bread#breadcrumb-behaviour-for-post-types-and-taxonomies) ?
This is an intended behaviour, the plugin was designed for WordPress not for Woocommerce (which is a sub extension).
In WordPress there is no category index page, on a WordPress blog accessing example.com/category/ result in a 404.

**Comment by hanyseyedy** [comment]
hi,
I'm set slug and url for the root crumb, but this does not solve the problem. 
Look at the screenshot below. In addition to root, it also adds the site url and this is not appropriate. Only Home is enough. There is no need for a "hanytheme project" anymore.

![sample-page](https://user-images.githubusercontent.com/36000819/155543673-6ce60392-a1d9-4607-91a1-f7e6915b60d8.png)

2- In the latter case, I did not mean WooCommerce, I just wanted to show that "Home" is placed on all pages and posts.

Regards

**Comment by amarinediary** [comment]
You're working on localhost, in a live site this won't show up.
Localhost breadcrumb:
```
Home > Theme > Sample page
```
Live breadcrumb:
```
Home > Sample page
```
Does that answer your question ? You can also take a look at [Localhost development issue](https://github.com/amarinediary/Where-Is-My-Bread#localhost-development-issue)

**Comment by hanyseyedy** [comment]
Oh. I didn't know! I thought there was a problem.
I really apologize for taking your time
