### ISSUE TITLE
Can't get the plugin to work properly

### ISSUE THREAD

**Issue by nikolailehbrink** [amarinediary/Where-Is-My-Bread#8]
Hi there, first off, thanks for the lightweight Plugin. I would really love to use it, but on my local site it only displays a php error when inserting the following code in singular.php:
```
	<?php

	$ingredients = array(
		'separator' => '→',
	);

	the_bread($ingredients);
	?>
```

### Warning: Undefined array key "REQUEST_SCHEME" in /Users/example/Local Sites/site/app/public/wp-content/plugins/Where-Is-My-Bread-main/where-is-my-bread.php on line 124

```
1 | 16789109378.5403 | 368904 | {main}( ) | .../index.php:0
2 | 16789109378.5403 | 369216 | require( '/Users/example/Local Sites/site/app/public/wp-blog-header.php ) | .../index.php:17
3 | 16789109378.5403 | 11755136 | require_once( '/Users/example/Local Sites/site/app/public/wp-includes/template-loader.php ) | .../wp-blog-header.php:19
4 | 16789109378.5403 | 11779600 | include( '/Users/example/Local Sites/site/app/public/wp-content/themes/theme/singular.php ) | .../template-loader.php:106
5 | 16789109378.5403 | 11991768 | the_bread( ) | .../singular.php:10
6 | 16789109378.5403 | 11991768 | get_the_crumbs( ) | .../where-is-my-bread.php:200

```
What do I do wrong?

**Comment by amarinediary** [comment]
That's interesting. `REQUEST_SCHEME` is a native variable of Apache web server since its version `2.4`. Naturally, if a variable is not set by the server, PHP will not include it in its global array `$_SERVER`.
Looking more deeply into the subject, keep you updated.

**Comment by amarinediary** [comment]
The following will be deployed in `1.0.7`. [View the changelog](https://github.com/amarinediary/Where-Is-My-Bread#107).
### In response to (2):
- - [x] Alternative way to determine the server scheme.

**Comment by amarinediary** [comment]
@nikolailehbrink I've published an update that should handle your case. Awaiting your feedback.

**Comment by nikolailehbrink** [comment]
HI, wow! That was fast! Thank you very much! It works fine and thanks for the lightweight plugin :)
