### ISSUE TITLE
Compatible with "older" php versions

### ISSUE THREAD

**Issue by nikolailehbrink** [amarinediary/Where-Is-My-Bread#9]
Hi I wondered, if you could make the plugin compatible with php-versions older than 8.0 since many sites are not ready to switch to v. 8 and I still wanted to install the plugin there! Thank you very much for the plugin :)

**Comment by amarinediary** [comment]
I've drafted [version 1.2.0](https://github.com/amarinediary/WordPress-simple-URL-based-breadcrumb/releases/tag/1.2.0) which should handle at least from PHP 7 (probably from PHP > 5). Let me know @nikolailehbrink.

- [x] Backward compatibility for PHP 7 (onwards) (Removed [`str_ends_with`](https://www.php.net/manual/en/function.str-ends-with.php) and [`str_contains`](https://www.php.net/manual/en/function.str-contains.php) native functions usage which were dependend on PHP > 8. Added `backward_compatibility_str_ends_with` and `backward_compatibility_str_contains` functions, as a mean to support PHP > 7).

**Comment by nikolailehbrink** [comment]
And again! Thanks for the fast immplementation! Works perfectly!
